{
  config,
  lib,
  pkgs,
  osConfig ? {},
  ...
}: let
  inherit (lib.modules) mkIf mkMerge;
  inherit (lib.options) mkOption mkEnableOption mkPackageOption;
  inherit (lib.types) attrsOf anything;

  cfg = config.rum.programs.btop;

  # Stylix integration - generate theme if Stylix is enabled
  stylixTheme = mkIf (osConfig.stylix.enable or false) {
    xdg.config.files."btop/themes/stylix.theme".text = let
      colors = osConfig.lib.stylix.colors.withHashtag;
    in ''
      # Generated by Stylix
      theme[main_bg]="${colors.base00}"
      theme[main_fg]="${colors.base05}"
      theme[title]="${colors.base05}"
      theme[hi_fg]="${colors.base0D}"
      theme[selected_bg]="${colors.base03}"
      theme[selected_fg]="${colors.base0D}"
      theme[inactive_fg]="${colors.base04}"
      theme[graph_text]="${colors.base06}"
      theme[meter_bg]="${colors.base03}"
      theme[proc_misc]="${colors.base06}"
      theme[cpu_box]="${colors.base0E}"
      theme[mem_box]="${colors.base0B}"
      theme[net_box]="${colors.base0C}"
      theme[proc_box]="${colors.base0D}"
      theme[div_line]="${colors.base01}"
      theme[temp_start]="${colors.base0B}"
      theme[temp_mid]="${colors.base0A}"
      theme[temp_end]="${colors.base08}"
      theme[cpu_start]="${colors.base0B}"
      theme[cpu_mid]="${colors.base0A}"
      theme[cpu_end]="${colors.base08}"
      theme[free_start]="${colors.base0A}"
      theme[free_mid]="${colors.base0B}"
      theme[free_end]="${colors.base0B}"
      theme[cached_start]="${colors.base0C}"
      theme[cached_mid]="${colors.base0C}"
      theme[cached_end]="${colors.base0A}"
      theme[available_start]="${colors.base08}"
      theme[available_mid]="${colors.base0A}"
      theme[available_end]="${colors.base0B}"
      theme[used_start]="${colors.base0A}"
      theme[used_mid]="${colors.base09}"
      theme[used_end]="${colors.base08}"
      theme[download_start]="${colors.base0B}"
      theme[download_mid]="${colors.base0A}"
      theme[download_end]="${colors.base08}"
      theme[upload_start]="${colors.base0B}"
      theme[upload_mid]="${colors.base0A}"
      theme[upload_end]="${colors.base08}"
      theme[process_start]="${colors.base0B}"
      theme[process_mid]="${colors.base0A}"
      theme[process_end]="${colors.base08}"
    '';
  };

  # Stylix settings integration
  stylixEnabled = osConfig.stylix.enable or false;
  stylixOpaque = (osConfig.stylix.opacity.terminal or 1.0) == 1.0;

  stylixSettings = lib.optionalAttrs stylixEnabled (
    {
      color_theme = "stylix";
    }
    // lib.optionalAttrs (!stylixOpaque) {
      theme_background = false;
    }
  );
in {
  options.rum.programs.btop = {
    enable = mkEnableOption "btop";

    package = mkPackageOption pkgs "btop" {nullable = true;};

    settings = mkOption {
      type = attrsOf anything;
      default = {};
      example = {
        color_theme = "TTY";
        theme_background = false;
        truecolor = true;
        vim_keys = true;
      };
      description = ''
        Configuration written to {file}`$XDG_CONFIG_HOME/btop/btop.conf`.

        See [btop's documentation] for available options.

        [btop's documentation]: https://github.com/aristocratos/btop#configurability
      '';
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      packages = mkIf (cfg.package != null) [cfg.package];

      xdg.config.files."btop/btop.conf".text = let
        toConfigLine = name: value: let
          valueStr =
            if lib.isBool value
            then
              (
                if value
                then "True"
                else "False"
              )
            else toString value;
        in "${name} = ${valueStr}";

        allSettings = stylixSettings // cfg.settings;
      in
        lib.concatStringsSep "\n" (lib.mapAttrsToList toConfigLine allSettings);
    }

    stylixTheme
  ]);
}
